# .github/workflows/smoke.yml
name: smoke

on: [push, pull_request, workflow_dispatch]

env:
  API: https://r3ddkahili-oplc-api.hf.space
  UI:  https://r3ddkahili-oplc-ui.hf.space

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Healthz (with retries)
        run: |
          for i in {1..5}; do
            if curl -fsS --max-time 10 "$API/healthz" | grep -xq 'ok'; then
              echo "healthz ok"; exit 0; fi
            echo "retry $i..." && sleep 5
          done
          echo "::error::/healthz failed after retries"; exit 1

      - name: Range check for known prefix (password)
        run: |
          curl -fsS --retry 3 --retry-all-errors "$API/range/5BAA6" \
            | grep -q '1E4C9B93F3F0682250B6CF8331B7EE68FD8'

      - name: Verify local SHA-1 (sanity)
        run: |
          python - <<'PY'
          import hashlib
          assert hashlib.sha1(b'password').hexdigest().upper() == '5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8'
          print('ok')
          PY

      - name: UI reachable (title or H1 present; case-insensitive; follow redirects)
        run: |
          HTML="$(curl -fsSL --retry 3 --retry-all-errors "$UI/?v=ci")"
          # debug snippet if it ever fails
          echo "$HTML" | head -n 40
          echo "$HTML" | tr -d '\r' | sed 's/&nbsp;/ /g' \
            | grep -qiE '<title>.*open password leak check.*</title>|open password leak check'
