name: smoke


on:
push:
pull_request:
workflow_dispatch:
schedule:
- cron: '18 */6 * * *' # every 6 hours for uptime


jobs:
test:
runs-on: ubuntu-latest
timeout-minutes: 5
steps:
- name: Check API /healthz
run: |
curl -sSf https://r3ddkahili-oplc-api.hf.space/healthz | grep -x 'ok'


- name: Check /range for known prefix (password)
run: |
curl -sSf https://r3ddkahili-oplc-api.hf.space/range/5BAA6 \
| grep -q '1E4C9B93F3F0682250B6CF8331B7EE68FD8'


- name: Verify client SHA-1 (hash of "password")
run: |
python - <<'PY'
import hashlib
h = hashlib.sha1(b'password').hexdigest().upper()
assert h == '5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8'
print('ok')
PY


- name: UI reachable
run: |
curl -sSf https://r3ddkahili-oplc-ui.hf.space/ | grep -q 'Open Password Leak Check'
